### ISSUE TITLE
Manual switch & PCB schematic

### ISSUE THREAD

**Issue by junaideqbal** [coredataglobal/RelayFi#1]
can we also add a manual switch in it? so the devices can be controlled both with manual and automation?

**Comment by junaideqbal** [comment]
Also I have seen that PCB schematic is not here, can you provide that to?

**Comment by coredataglobal** [comment]
Hi @junaideqbal , Yes you can connect the manual switch using the I2C connector Pins GPIO or by removing the jumper and connecting it with the manual switch (either 5v or GND).  You can also find the PCB schematic inside the schematic folder.

https://github.com/coredataglobal/RelayFi/blob/main/Schematic/Schematic_RelayFi.pdf
